sonar.projectKey=artpalau_ha-telegram-bot
sonar.organization=artpalau

sonar.sources=src
sonar.language=python

# Uncomment and set these when you add tests and coverage reporting:
# sonar.tests=tests
# sonar.python.coverage.reportPaths=coverage.xml
